platform :ios do
  desc "Shasco Sports Firebase Deploy"
    lane :ios_beta_app do
        build_app(
            scheme: "Runner",
            archive_path: "./build/Runner.xcarchive",
            export_method: "development",
            output_directory: "./build/Runner"
        )
        firebase_app_distribution(
            app: "1:196400689661:ios:7ce124b22cd2baf34a2994",
            testers: "shanesblume@gmail.com, lblume613@gmail.com",
            release_notes: "Initial version of the app",
            firebase_cli_path: "/usr/local/bin/firebase",
            ipa_path: "./build/Runner/Runner.ipa"
        )
    end
end