default_platform(:android)

platform :android do
  desc "Shasco Sports Firebase Deploy"
  gradle(
      task: 'assemble',
      build_type: 'Release'
  )
  lane :android_beta_app do
      firebase_app_distribution(
          app: "1:196400689661:android:67f14d7a80351fd94a2994",
          testers: "shanesblume@gmail.com, lblume613@gmail.com",
          release_notes: "Initial version of the app",
          firebase_cli_path: "/usr/local/bin/firebase",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end
